### ISSUE TITLE
最低支持android 4.4 API 19

### ISSUE THREAD

**Issue by lealife** [leanote/leanote-android#4]
当前是 5.0 API 21

**Comment by lealife** [comment]
@xingstarx 👍

**Comment by xingstarx** [comment]
测试了下，兼容到android4.2(api 17) 会在webview js调用那块出问题,暂时就先兼容到api19

兼容到android 4.4(api 19)不用做大的改动，直接就可以

**Comment by xingstarx** [comment]
@houxg  @nicacol  可以都测试一下

**Comment by lealife** [comment]
4.4 就行

**Comment by lealife** [comment]
@xingstarx 到4.4要改哪些?

**Comment by xingstarx** [comment]
额，已经改了，都合并了。什么都不需要改动。。

**Comment by lealife** [comment]
👍 有没有真机测试呢?

**Comment by xingstarx** [comment]
当然有啊。。这是必须的。

**Comment by lealife** [comment]
👍 👍

**Comment by lealife** [comment]
@xingstarx 4.4.4下, 点击搜索笔记出现:
```

                                                                         at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
                                                                         at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:155)
                                                                         at android.view.View.performClick(View.java:4444)
                                                                         at android.view.View$PerformClick.run(View.java:18457)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5034)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                         at dalvik.system.NativeStart.main(Native Method)
```

**Comment by xingstarx** [comment]
好的，我中午看看

**Comment by lealife** [comment]
切换用户也出现:
```
02-17 11:10:39.665 21721-21721/com.leanote.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.leanote.android, PID: 21721
                                                                     java.lang.NoSuchMethodError: android.graphics.drawable.Drawable.setHotspot
                                                                         at org.houxg.leamonax.ui.Navigation$4.onAnimationEnd(Navigation.java:207)
                                                                         at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1030)
                                                                         at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
                                                                         at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
                                                                         at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
                                                                         at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:543)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5034)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                         at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lealife** [comment]
我是用最新的源码build的.
![image](https://cloud.githubusercontent.com/assets/1699428/23051414/d51c988a-f503-11e6-92ef-4c59b7842a43.png)

**Comment by houxg** [comment]
- `Drawable.setHotspot()` API21才加入的
- `ActivityOptions`可以考虑采用`ActivityCompact`
