### ISSUE TITLE
SQLiteBlobTooBigException

### ISSUE THREAD

**Issue by xingstarx** [leanote/leanote-android#82]
```
java.lang.RuntimeException: Unable to resume activity {com.leanote.android/org.houxg.leamonax.ui.MainActivity}: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=5, totalRows=6
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3824)
  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3856)
  at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6806)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=5, totalRows=6
  at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
  at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
  at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
  at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
  at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:159)
  at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
  at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
  at android.database.AbstractCursor.moveToNext(AbstractCursor.java:275)
  at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.convertToData(ListModelLoader.java:35)
  at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.convertToData(ListModelLoader.java:15)
  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:69)
  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:57)
  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:51)
  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:35)
  at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:53)
  at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:237)
  at org.houxg.leamonax.database.NoteDataStore.getAllNotes(NoteDataStore.java:134)
  at org.houxg.leamonax.ui.NoteFragment.setMode(NoteFragment.java:157)
  at org.houxg.leamonax.ui.MainActivity.onShowNotes(MainActivity.java:181)
  at org.houxg.leamonax.ui.Navigation.refresh(Navigation.java:466)
  at org.houxg.leamonax.ui.Navigation.onResume(Navigation.java:497)
  at org.houxg.leamonax.ui.MainActivity.onResume(MainActivity.java:114)
  at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
  at android.app.Activity.performResume(Activity.java:7366)
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3816)
  ... 11 more

```

**Comment by xingstarx** [comment]
https://stackoverflow.com/questions/51959944/sqliteblobtoobigexception-row-too-big-to-fit-into-cursorwindow-requiredpos-0-t
